Get files for IX component

diff --git a/src/submit b/src/submit
--- a/src/submit
+++ b/src/submit
@@ -1,442 +1,232 @@
-#!/bin/sh 
+#!/bin/bash
 
-# Usage: submit <-c or -s> <HW #>'
-#
-# The "HW #" should be the homework number for the current '
-# submission.  The submit program uses the homework number to '
-# automatically locate most of the files in the submission.'  
-#
-# c - Collect the files that are to be submitted.  '
-#     This argument causes the file submit.<Component Initials> to be 
-#     created and displayed containing a list of the files that will get'
-#     submitted by this script.'
+# Usage: submit <-c or -s> <HW #>
 # 
-# s - Submit the files. '
+# c - Collect the files that are to be submitted.
+#     This argument causes the file submit.<Component Initials> to be
+#     created and displayed containing a list of the files that will get
+#     submitted by this script.
+# 
+# s - Submit the files.
 #     This argument causes the files listed in submit.<Component Initials>
-#     to be submitted.  If submit.<Component Initials> does not exist, it is'
-#     created as for argument c.'
+#     to be submitted.  If submit.<Component Initials> does not exist, it is
+#     created as for argument c.
 # 
-#     It is possible to call this script with argument "-c", edit the'
-#     temporary file in case it does not contain the correct files,'
+#     It is possible to call this script with argument "-c", edit the
+#     temporary file in case it does not contain the correct files,
 #     and then call the script with argument "-s" to submit the files.
-#
-# The number should be:'
-#   1 - RM (Record Manager)'
-#   2 - IX (Index Manager)'
-#   3 - SM (Session Manager)'
-#   4 - QL (Query Language)'
-#   5 - EX (Extension)'
-#
-# The HW # is required every time that submit is run.'
-#
+# 
+# The "HW #" should be the homework number for the current
+# submission.  The submit program uses the homework number to
+# automatically locate most of the files in the submission.
+# 
+# The number should be:
+#   1 - RM (Record Manager)
+#   2 - IX (Index Manager)
+#   3 - SM (Session Manager)
+#   4 - QL (Query Language)
+#   5 - EX (Extension)
+# 
+# The HW # is required every time that submit is run.
+# 
+# END OF USAGE
 
-# make sure all commands in this script always runs the expected executables
-PATH=/usr/bin:/bin:$PATH
+# abort when anything goes wrong or an unset variable was used
+set -eu
 
-# HWNUM is the second argument to this shell script
-HWNUM=$2
-
-if [ "$2" = "1" ]
-then
-  PREFIX=rm
-  PREFIXU=RM
-elif [ "$2" = "2" ]
-then
-  PREFIX=ix
-  PREFIXU=IX
-elif [ "$2" = "3" ]
-then
-  PREFIX=sm
-  PREFIXU=SM
-elif [ "$2" = "4" ]
-then
-  PREFIX=ql
-  PREFIXU=QL
-elif [ "$2" = "5" ]
-then
-  PREFIX=ex
-  PREFIXU=EX
-else
-  echo
-  echo "submit::HW # argument not correctly specified"
-  echo
-  PREFIX=NONE
-fi
-
-SUBMIT_FILE='submit.'$PREFIX
-README=$PREFIX'_DOC'
-SOURCE_PATTERN=$PREFIX'.*\.[c|h]c?x*$'
-MAKEFILE_PATTERN='[M|m]ake'
-DOT_H_PATTERN='\.h$'
-INCLUDE=$PREFIX'.h'
-
-REDBASE=redbase.h
-
-# Corn machine does not have /usr/tmp
-#BUFHOME=/usr/tmp
-BUFHOME=/tmp
-
-STUDENT=$USER
-BUFDIR=$BUFHOME/$STUDENT.cs346.$$.dir
-BUFTAR=$BUFHOME/$STUDENT.cs346.$$.tar
-
+## Sanitize environment and set variables
+# make sure all commands in this script always runs the expected executables in the expected ways
+PATH=/usr/bin:/bin
+unset LD_PRELOAD
+# and all created files aren't readable by others
 umask 077
 
-# Check for just one of the options - either "-c" or "-s"!
-if [ "$1" = '-c' ]
+# directory to collect submissions
+SUBMIT_PATH=/usr/class/cs346/redbase/submissions
+# default temporary directory
+: ${TMPDIR:=/tmp}
+
+## Some shorthands for showing messages
+color() {
+    # print color code when stdout is a tty
+    ! [ -t 1 ] ||
+    case $1 in
+        red)     echo -ne $'\\E[1;31m' ;;
+        green)   echo -ne $'\\E[1;32m' ;;
+        default) echo -ne $'\\E[0m'    ;;
+    esac
+}
+error() {
+    {
+        color red
+        echo "ERROR:" "$@"
+        color default
+    } >&2
+    false
+}
+usage() {
+    # Show the usage embedded as a block of comments in this script
+    sed -n '/# Usage: /,/# END OF USAGE/{ /# END OF USAGE/q; s/^# //p; }' <"$0"
+    [ $# -eq 0 ] || error "$@"
+}
+
+## Parse arguments
+# The first argument should be either -c or -s
+Mode=${1:-}
+is_verifying=false
+is_submitting=false
+case $Mode in
+    -c) is_verifying=true ;;
+    -s) is_submitting=true ;;
+    "") usage "Either -c or -s must be specified." ;;
+    *)
+        usage "Invalid first argument: '$Mode'"
+esac
+
+# The second argument is HW #
+HwNum=${2:-}
+case $HwNum in
+    "1") Part=rm ;;
+    "2") Part=ix ;;
+    "3") Part=sm ;;
+    "4") Part=ql ;;
+    "5") Part=ex ;;
+    "") usage "HW # argument must be specified." ;;
+    *) Part=NONE
+        usage "HW # argument not correctly specified: '$HwNum'"
+esac
+
+
+## Find the redbase root dir created by the setup script
+redbase_root_reached() { [ -d src -a -d lib -a -d build ]; }
+until redbase_root_reached || [ $PWD = / ]
+do cd ..
+done
+redbase_root_reached ||
+    error "You should first 'cd' to the directory containing your source code."
+
+
+
+## Prepare a list of file for submission
+filelist=src/submit.${Part}.txt
+# Create a new list of files for submission if it doesn't exist or when in checking mode
+if ! [ -r "$filelist" ] || {
+        $is_verifying &&
+        read -n 1 -p "Overwrite ${filelist}? ([Y]es/[n]o) " &&
+        echo &&
+        case $REPLY in [yY]) true ;; *) false ;; esac
+    }
 then
-  VERIFY=yes
+    # Confirm overwriting before proceeding
+    # Create a new default list of files
+    should_submit() {
+        local found=false file=
+        for file; do
+            if [ -r "$file" ]; then
+                echo "$file" >>"$filelist".tmp
+                found=true
+            fi
+        done
+        $found ||
+            if [ $# -eq 1 ]; then
+                error "$file not found but should be submitted!"
+            else
+                error "None of these files are found: $*.  At least one of them should be submitted!"
+            fi
+    }
+    rm -f "$filelist".tmp
+    echo "Creating ${filelist}..."
+    # documentation
+    should_submit src/${Part}_DOC
+    # source files for the part
+    should_submit src/$Part*.{h,cc,C,cxx,cpp}
+    should_submit src/Makefile
+    case $Part in
+        ex|ql|sm) # later parts: 3-5
+            # redbase executables and their sources (whose name doesn't start with $Part)
+            should_submit src/redbase.{cc,C,cxx,cpp}
+            should_submit src/dbcreate.{cc,C,cxx,cpp}
+            should_submit src/dbdestroy.{cc,C,cxx,cpp}
+            should_submit src/redbase
+            should_submit src/dbcreate
+            should_submit src/dbdestroy
+            ;;
+        ix) # part 2
+            should_submit src/rm_rid.h
+            should_submit src/rm.h
+            should_submit src/pf.h
+            should_submit src/redbase.h
+            should_submit lib/libix.a
+            should_submit lib/librm.a
+            should_submit lib/libpf.a
+            ;;
+        rm) # part 1
+            should_submit src/pf.h
+            should_submit src/redbase.h
+            should_submit lib/librm.a
+            should_submit lib/libpf.a
+            ;;
+    esac
+    # rest of the source files
+    should_submit src/*.{h,cc,C,cxx,cpp,c,y,l}
+
+    # drop duplicate entires in the file list
+    awk '!seen[$0]++ {print $0}' <"$filelist".tmp >"$filelist"
+    rm -f "$filelist".tmp
+fi
+
+## Submit files listed in $filelist
+if $is_submitting; then
+
+    # Sanity check of environment before proceeding
+    case $(hostname) in
+        corn[0-9]*.stanford.edu|cardinal*.stanford.edu|myth[0-9]*.stanford.edu)
+            [ -d "$SUBMIT_PATH" ] ||
+                error "Submission destination ($SUBMIT_PATH) does not exist!"
+            ;;
+        *)
+            error "This script can only be run from one of the FarmShare or CS (corn, cardinal, or myth) machines."
+            ;;
+    esac
+
+    # Prepare a temporary directory for staging and creating tarball
+    tmpdir=$(mktemp -d ${TMPDIR:-/tmp}/redbase-submit.XXXXXX)
+    trap "rm -rf $tmpdir" EXIT
+    stagedir=$tmpdir/stage
+    tarball=$tmpdir/$USER.$HwNum-$Part.$(date +%Y%m%d-%H%M%S).tar.gz
+
+    # Stage the files enumerated in $filelist
+    echo "Copying your files to ${stagedir}/..."
+    while read filename; do
+        d="$stagedir/$(dirname "$filename")"
+        mkdir -p "$d"
+        echo "  $filename"
+        cp -p "$filename" "$d"/ ||
+            error "Could not make a copy of ${filename}. Make sure you have correctly listed it in ${filelist}."
+    done <"$filelist"
+
+    # Create a tarball of the staged ones.
+    echo "Creating ${tarball}..."
+    tar czf "$tarball" -C "$stagedir" .
+
+    # Submit the files to the submission directory.
+    echo "Placing it under $SUBMIT_PATH/..."
+    mv -f "$tarball" "$SUBMIT_PATH"/
+
+    color green
+    echo
+    echo "SUCCESS! Your work for RedBase Part ${HwNum} (${Part}) has been submitted."
+    color default
+
+## Or, just show the list of files to be submitted
 else
-  VERIFY=no
+    cat "$filelist"
+
+    cat <<-EOF
+	
+	Verify that all of your source files, libraries (*.a), and
+	executables that need to be submitted are listed above.
+	Edit the file '$filelist' to include files that are missing.
+	Execute 'submit -s <HW #>' to submit the files.
+	EOF
 fi
-
-if [ "$1" = '-s' ]
-then
-  SUBMIT=yes
-else
-  SUBMIT=no
-fi
-
-# Verify we're doing either a verify or a submit and that
-# the user has entered a valid Homework number.
-
-if [ $VERIFY = no -a $SUBMIT = no -o $PREFIX = "NONE" ]
-then
-  echo 'Usage: submit <-c or -s> <HW #>'
-  echo
-  echo 'c - Collect the files that are to be submitted.  '
-  echo '    This argument causes the file submit.<Component Initials> to be '
-  echo '    created and displayed containing a list of the files that will get'
-  echo '    submitted by this script.'
-  echo
-  echo 's - Submit the files. '
-  echo '    This argument causes the files listed in submit.<Component Initials>'
-  echo '    to be submitted.  If submit.<Component Initials> does not exist, it is'
-  echo '    created as for argument c.'
-  echo
-  echo '    It is possible to call this script with argument "-c", edit the'
-  echo '    temporary file in case it does not contain the correct files,'
-  echo '    and then call the script with argument "-s" to submit the files.'
-  echo 
-  echo 'The "HW #" should be the homework number for the current '
-  echo 'submission.  The submit program uses the homework number to '
-  echo 'automatically locate most of the files in the submission.'  
-  echo
-  echo 'The number should be:'
-  echo '  1 - RM (Record Manager)'
-  echo '  2 - IX (Index Manager)'
-  echo '  3 - SM (Session Manager)'
-  echo '  4 - QL (Query Language)'
-  echo '  5 - EX (Extension)'
-  echo
-  echo 'The HW # is required every time that submit is run.'
-  echo
-  exit 1
-fi
-
-# Verify we're in the correct directory (doesn't apply to extension)
-
-if [ ! -r $README ]
-then
-  echo 'Error: ' $README ' file not found.'
-  echo 'You should first "cd" to the directory containing your source code.'
-  exit 1
-fi
-
-if [ $HWNUM -le 4 ]
-then
-  if [ ! -r $INCLUDE ]
-  then
-    echo 'Error: ' $INCLUDE ' file not found.'
-    exit 1
-  fi
-fi
-
-# Should we create the $SUBMIT_FILE file?
-
-if [ $VERIFY = yes -o ! -r $SUBMIT_FILE ]
-then
-  rm $SUBMIT_FILE
-  echo 'Creating ' $SUBMIT_FILE
-
-  # Get documentation file
-
-  echo $README > $SUBMIT_FILE
-
-  # Get main include file
-
-  if [ $HWNUM -le 2 ]
-  then 
-    if [ -r $REDBASE ]
-    then
-      echo $REDBASE >> $SUBMIT_FILE
-    elif [ -r ../$REDBASE ]
-    then
-      echo ../$REDBASE >> $SUBMIT_FILE
-    elif [ -r ../pf/$REDBASE ]
-    then
-      echo ../pf/$REDBASE >> $SUBMIT_FILE
-    else
-      echo 'Error: ' $REDBASE ' file not found.'
-      echo 'Searched current directory, ../, and ../pf/.'
-      exit 1
-    fi
-  fi
-
-  # Get include files for previous components
-
-  if [ $HWNUM -le 2 ]
-  then
-    if [ -r pf.h ]
-    then
-      echo pf.h >> $SUBMIT_FILE
-    elif [ -r ../pf/pf.h ]
-    then
-      echo ../pf/pf.h >> $SUBMIT_FILE
-    elif [ -r ../include/pf.h ]
-    then
-      echo ../include/pf.h >> $SUBMIT_FILE
-    else
-      echo 'Error: pf.h file not found.'
-      echo 'Searched current directory, ../pf/, and ../include/.'
-      exit 1
-    fi
-  fi
-
-  if [ $HWNUM -eq 2 ]
-  then
-    if [ -r rm_rid.h ]
-    then
-      echo rm_rid.h >> $SUBMIT_FILE
-    else
-      echo 'Error: rm_rid.h file not found in current directory.'
-      exit 1
-    fi
-  fi
-
-  if [ $HWNUM -eq 2 ]
-  then
-    if [ -r rm.h ]
-    then
-      echo rm.h >> $SUBMIT_FILE
-    elif [ -r ../rm/rm.h ]
-    then
-      echo ../rm/rm.h >> $SUBMIT_FILE
-    elif [ -r ../include/rm.h ]
-    then
-      echo ../include/rm.h >> $SUBMIT_FILE
-    else
-      echo 'Error: rm.h file not found.'
-      echo 'Searched current directory, ../rm/, and ../include/.'
-      exit 1
-    fi
-  fi
-
-  # Get libraries
-
-  if [ $HWNUM -le 2 ]
-  then
-    if [ -r libpf.a ]
-    then
-      echo libpf.a >> $SUBMIT_FILE
-    elif [ -r ../pf/libpf.a ]
-    then
-      echo ../pf/libpf.a >> $SUBMIT_FILE
-    elif [ -r ../lib/libpf.a ]
-    then
-      echo ../lib/libpf.a >> $SUBMIT_FILE
-    else
-      echo 'Error: libpf.a file not found.'
-      echo 'Searched current directory, ../pf/, and ../lib/.'
-      exit 1
-    fi
-  fi
-
-  if [ $HWNUM -le 2 ]
-  then
-    if [ -r librm.a ]
-    then
-      echo librm.a >> $SUBMIT_FILE
-    elif [ -r ../rm/librm.a ]
-    then
-      echo ../rm/librm.a >> $SUBMIT_FILE
-    elif [ -r ../lib/librm.a ]
-    then
-      echo ../lib/librm.a >> $SUBMIT_FILE
-    else
-      echo 'Error: librm.a file not found.'
-      echo 'Searched current directory, ../rm/, and ../lib/.'
-      exit 1
-    fi
-  fi
-
-  if [ $HWNUM -eq 2 ]
-  then
-    if [ -r libix.a ]
-    then
-      echo libix.a >> $SUBMIT_FILE
-    elif [ -r ../ix/libix.a ]
-    then
-      echo ../ix/libix.a >> $SUBMIT_FILE
-    elif [ -r ../lib/libix.a ]
-    then
-      echo ../lib/libix.a >> $SUBMIT_FILE
-    else
-      echo 'Error: libix.a file not found.'
-      echo 'Searched current directory, ../ix/, and ../lib/.'
-      exit 1
-    fi
-  fi
-
-  # Get redbase executables
-
-  if [ $HWNUM -eq 3 -o $HWNUM -eq 4 ]
-  then
-    if [ -r redbase ]
-    then 
-      echo redbase >> $SUBMIT_FILE
-    elif [ -r ../redbase ]
-    then
-      echo ../redbase >> $SUBMIT_FILE
-    elif [ -r ../dm/redbase ]
-    then
-      echo ../dm/redbase >> $SUBMIT_FILE
-    else
-      echo 'Error: redbase executable not found.'
-      echo 'Searched current directory, ../, and ../dm/.'
-      exit 1
-    fi
-
-    if [ -r dbcreate ]
-    then 
-      echo dbcreate >> $SUBMIT_FILE
-    elif [ -r ../dbcreate ]
-    then
-      echo ../dbcreate >> $SUBMIT_FILE
-    elif [ -r ../dm/dbcreate ]
-    then
-      echo ../dm/dbcreate >> $SUBMIT_FILE
-    else
-      echo 'Error: dbcreate executable not found.'
-      echo 'Searched current directory, ../, and ../dm/.'
-      exit 1
-    fi
-
-    if [ -r dbdestroy ]
-    then 
-      echo dbdestroy >> $SUBMIT_FILE
-    elif [ -r ../dbdestroy ]
-    then
-      echo ../dbdestroy >> $SUBMIT_FILE
-    elif [ -r ../dm/dbdestroy ]
-    then
-      echo ../dm/dbdestroy >> $SUBMIT_FILE
-    else
-      echo 'Error: dbdestroy executable not found.'
-      echo 'Searched current directory, ../, and ../dm/.'
-      exit 1
-    fi
-  fi
-
-  # Get redbase executable sources (files might not start with dm)
-
-  if [ $HWNUM -eq 3 ]
-  then
-    if [ -r redbase.cc ]
-    then
-      echo redbase.cc >> $SUBMIT_FILE
-    elif [ -r redbase.C ]
-    then
-      echo redbase.C >> $SUBMIT_FILE
-    fi
-    if [ -r dbcreate.cc ]
-    then
-      echo dbcreate.cc >> $SUBMIT_FILE
-    elif [ -r dbcreate.C ]
-    then
-      echo dbcreate.C >> $SUBMIT_FILE
-    fi
-    if [ -r dbdestroy.cc ]
-    then
-      echo dbdestroy.cc >> $SUBMIT_FILE
-    elif [ -r dbdestroy.C ]
-    then
-      echo dbdestroy.C >> $SUBMIT_FILE
-    fi
-  fi
-
-  # Get source files
-
-# SOURCE_PATTERN=$PREFIX'.*\.[c|h]c?x*$'
-  ls | egrep -iw $SOURCE_PATTERN >> $SUBMIT_FILE
-  ls | egrep -i $MAKEFILE_PATTERN >> $SUBMIT_FILE
-  ls | egrep -i $DOT_H_PATTERN >> $SUBMIT_FILE
-
-fi
-
-# Cat $SUBMIT_FILE
-
-echo
-cat $SUBMIT_FILE
-echo
-
-# Should we submit the files?
-
-if [ $SUBMIT = yes ]
-then
-
-  # Copy the files to $BUFDIR
-
-  echo Copying your files to '"'$BUFDIR/'"'
-
-  mkdir $BUFDIR
-  cat $SUBMIT_FILE | while read s
-  do
-    cp -p $s $BUFDIR
-  done
-
-  # Tar the files
-
-  SRCDIR=`pwd`
-  cd $BUFDIR
-  echo Collecting in '"'$BUFTAR'"'
-  tar cfv $BUFTAR *
-  cd $SRCDIR
-
-  echo -n '(Removing "'$BUFDIR/'" ...)'
-  rm -r $BUFDIR
-  echo
-
-  echo 'Compressing the submission.'
-  # Compress the files
- 
-  gzip $BUFTAR
-
-  # Submit the files to the submission directory
-  echo 'Placing your submitted files.'
-
-  cp $BUFTAR'.gz' /usr/class/cs346/redbase/submissions
-
-  echo
-  echo Work for assignment '#'$HWNUM submitted.
-  echo
-
-  # remove the tar file
-  echo -n '(Removing "'$BUFTAR/'" ...)'
-  rm $BUFTAR'.gz'
-  echo
-
-  case $(hostname) in
-    "corn"[0-9]*".stanford.edu") ;;
-    *)echo "#############################################################"
-      echo "##   !!! WARNING : This seems to be not corn machine !!!   ##"
-      echo "#############################################################" ;;
-  esac
-
-else
-  echo 'Verify that all of your source files and libraries (*.a) are listed.'
-  echo 'Edit the file "'$SUBMIT_FILE'" to include files that are missing.'
-  echo 'Execute "submit -s [HW #]" to submit the files.'
-  echo
-fi
-
